apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: btest
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: btest 
  name: btest
  namespace:  btest 
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: btest
    weight: 100 
